-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.acc_tokens_3legged (
  id integer NOT NULL DEFAULT nextval('acc_tokens_3legged_id_seq'::regclass),
  usuario_id integer NOT NULL,
  token_acceso text NOT NULL,
  token_refresco text,
  tipo_token character varying DEFAULT 'Bearer'::character varying,
  expira_en timestamp without time zone NOT NULL,
  estado integer DEFAULT 1,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT acc_tokens_3legged_pkey PRIMARY KEY (id),
  CONSTRAINT acc_tokens_3legged_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.accasignacionesincidencias (
  id bigint NOT NULL DEFAULT nextval('accasignacionesincidencias_id_seq'::regclass),
  issueid character varying NOT NULL,
  projectid character varying NOT NULL,
  idusuarioasignado integer NOT NULL,
  idusuarioasignador integer,
  fechaasignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accasignacionesincidencias_pkey PRIMARY KEY (id),
  CONSTRAINT accasignacionesincidencias_idusuarioasignado_fkey FOREIGN KEY (idusuarioasignado) REFERENCES public.authusuarios(id),
  CONSTRAINT accasignacionesincidencias_idusuarioasignador_fkey FOREIGN KEY (idusuarioasignador) REFERENCES public.authusuarios(id),
  CONSTRAINT accasignacionesincidencias_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT accasignacionesincidencias_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.accpermissionlevels (
  id integer NOT NULL DEFAULT nextval('accpermissionlevels_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  level integer NOT NULL UNIQUE,
  permissions jsonb,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accpermissionlevels_pkey PRIMARY KEY (id),
  CONSTRAINT accpermissionlevels_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT accpermissionlevels_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.accrecursosusuarios (
  id bigint NOT NULL DEFAULT nextval('accrecursosusuarios_id_seq'::regclass),
  recursotipo character varying NOT NULL,
  recursoid character varying NOT NULL,
  recursourn text,
  projectid character varying,
  parentid character varying,
  idusuariocreador integer,
  idusuarioasignado integer,
  idusuariomodifico integer,
  nombre text,
  descripcion text,
  estadorecurso character varying,
  metadatos jsonb,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accrecursosusuarios_pkey PRIMARY KEY (id),
  CONSTRAINT accrecursosusuarios_idusuariocreador_fkey FOREIGN KEY (idusuariocreador) REFERENCES public.authusuarios(id),
  CONSTRAINT accrecursosusuarios_idusuarioasignado_fkey FOREIGN KEY (idusuarioasignado) REFERENCES public.authusuarios(id),
  CONSTRAINT accrecursosusuarios_idusuariomodifico_fkey FOREIGN KEY (idusuariomodifico) REFERENCES public.authusuarios(id),
  CONSTRAINT accrecursosusuarios_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT accrecursosusuarios_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.accresources (
  id integer NOT NULL DEFAULT nextval('accresources_id_seq'::regclass),
  externalid character varying NOT NULL UNIQUE,
  resourcetype character varying NOT NULL,
  name character varying NOT NULL,
  parentid bigint,
  accountid character varying DEFAULT NULL::character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accresources_pkey PRIMARY KEY (id),
  CONSTRAINT accresources_parentid_fkey FOREIGN KEY (parentid) REFERENCES public.accresources(id),
  CONSTRAINT accresources_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT accresources_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.audacciones (
  id integer NOT NULL DEFAULT nextval('audacciones_id_seq'::regclass),
  codigo character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  descripcion text,
  idcategoria integer,
  plantillamensaje text,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audacciones_pkey PRIMARY KEY (id),
  CONSTRAINT audacciones_idcategoria_fkey FOREIGN KEY (idcategoria) REFERENCES public.audcategorias(id),
  CONSTRAINT audacciones_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT audacciones_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.audauditoria (
  id bigint NOT NULL DEFAULT nextval('audauditoria_id_seq'::regclass),
  idusuario integer NOT NULL,
  accion character varying NOT NULL,
  entidad character varying NOT NULL,
  identidad bigint,
  descripcion text,
  datosanteriores jsonb,
  datosnuevos jsonb,
  ipaddress character varying,
  useragent text,
  metadatos jsonb,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audauditoria_pkey PRIMARY KEY (id),
  CONSTRAINT audauditoria_idusuario_fkey FOREIGN KEY (idusuario) REFERENCES public.authusuarios(id),
  CONSTRAINT audauditoria_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT audauditoria_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.audcategorias (
  id integer NOT NULL DEFAULT nextval('audcategorias_id_seq'::regclass),
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  color character varying,
  icono character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audcategorias_pkey PRIMARY KEY (id),
  CONSTRAINT audcategorias_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT audcategorias_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.authpermisos (
  id integer NOT NULL DEFAULT nextval('authpermisos_id_seq'::regclass),
  nombre character varying NOT NULL,
  descripcion character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authpermisos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_permisos_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_permisos_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.authroles (
  id integer NOT NULL DEFAULT nextval('authroles_id_seq'::regclass),
  nombre character varying NOT NULL,
  descripcion character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authroles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_roles_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_roles_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.authrolespermisos (
  id integer NOT NULL DEFAULT nextval('authrolespermisos_id_seq'::regclass),
  idrol integer NOT NULL,
  idpermiso integer NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authrolespermisos_pkey PRIMARY KEY (id),
  CONSTRAINT authrolespermisos_idrol_fkey FOREIGN KEY (idrol) REFERENCES public.authroles(id),
  CONSTRAINT authrolespermisos_idpermiso_fkey FOREIGN KEY (idpermiso) REFERENCES public.authpermisos(id),
  CONSTRAINT authrolespermisos_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT authrolespermisos_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.authsesiones (
  id integer NOT NULL DEFAULT nextval('authsesiones_id_seq'::regclass),
  idusuario integer NOT NULL,
  token character varying UNIQUE,
  ip character varying,
  useragent text,
  fechainicio timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechafin timestamp without time zone,
  duracion interval DEFAULT (fechafin - fechainicio),
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authsesiones_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sesiones_usuario FOREIGN KEY (idusuario) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_sesiones_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_sesiones_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.authusuarios (
  id integer NOT NULL DEFAULT nextval('authusuarios_id_seq'::regclass),
  nombre character varying NOT NULL,
  correo character varying NOT NULL UNIQUE,
  contrasena character varying NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fotoperfil character varying DEFAULT NULL::character varying,
  CONSTRAINT authusuarios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.authusuariosroles (
  id integer NOT NULL DEFAULT nextval('authusuariosroles_id_seq'::regclass),
  idusuario integer NOT NULL,
  idrol integer NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authusuariosroles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_usuarios_roles_usuario FOREIGN KEY (idusuario) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_usuarios_roles_rol FOREIGN KEY (idrol) REFERENCES public.authroles(id),
  CONSTRAINT fk_usuarios_roles_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_usuarios_roles_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.empempresa (
  id integer NOT NULL DEFAULT nextval('empempresa_id_seq'::regclass),
  razonsocial character varying NOT NULL,
  nombrecomercial character varying,
  idtipodocumento integer NOT NULL,
  nrodocumento character varying NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT empempresa_pkey PRIMARY KEY (id),
  CONSTRAINT empempresa_idtipodocumento_fkey FOREIGN KEY (idtipodocumento) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT empempresa_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT empempresa_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genlistado (
  id integer NOT NULL DEFAULT nextval('genlistado_id_seq'::regclass),
  nombre character varying NOT NULL,
  descripcion character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genlistado_pkey PRIMARY KEY (id),
  CONSTRAINT fk_listado_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_listado_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genlistadoopciones (
  id integer NOT NULL DEFAULT nextval('genlistadoopciones_id_seq'::regclass),
  idlista integer NOT NULL,
  nombre character varying NOT NULL,
  descripcion character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genlistadoopciones_pkey PRIMARY KEY (id),
  CONSTRAINT fk_opciones_lista FOREIGN KEY (idlista) REFERENCES public.genlistado(id),
  CONSTRAINT fk_opciones_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_opciones_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genmenu (
  id integer NOT NULL DEFAULT nextval('genmenu_id_seq'::regclass),
  nombre character varying NOT NULL,
  url character varying,
  icono character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genmenu_pkey PRIMARY KEY (id),
  CONSTRAINT fk_roles_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_roles_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genmenuopciones (
  id integer NOT NULL DEFAULT nextval('genmenuopciones_id_seq'::regclass),
  idmenu integer NOT NULL,
  nombre character varying NOT NULL,
  url character varying,
  icono character varying,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genmenuopciones_pkey PRIMARY KEY (id),
  CONSTRAINT fk_menu_opciones_menu FOREIGN KEY (idmenu) REFERENCES public.genmenu(id),
  CONSTRAINT fk_roles_creacion FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT fk_roles_modificacion FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genmenurecursivo (
  id integer NOT NULL DEFAULT nextval('genmenurecursivo_id_seq'::regclass),
  idpadre integer,
  nombre character varying NOT NULL,
  url character varying,
  icono character varying,
  orden integer DEFAULT 0,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genmenurecursivo_pkey PRIMARY KEY (id),
  CONSTRAINT genmenurecursivo_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id),
  CONSTRAINT genmenurecursivo_idpadre_fkey FOREIGN KEY (idpadre) REFERENCES public.genmenurecursivo(id),
  CONSTRAINT genmenurecursivo_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.genmenuroles (
  id integer NOT NULL DEFAULT nextval('genmenuroles_id_seq'::regclass),
  idmenu integer NOT NULL,
  idrol integer NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT genmenuroles_pkey PRIMARY KEY (id),
  CONSTRAINT genmenuroles_idmenu_fkey FOREIGN KEY (idmenu) REFERENCES public.genmenurecursivo(id),
  CONSTRAINT genmenuroles_idrol_fkey FOREIGN KEY (idrol) REFERENCES public.authroles(id),
  CONSTRAINT genmenuroles_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT genmenuroles_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.notificacionespendientes (
  id bigint NOT NULL DEFAULT nextval('notificacionespendientes_id_seq'::regclass),
  idusuario integer NOT NULL,
  tipo character varying NOT NULL,
  titulo character varying NOT NULL,
  mensaje text,
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  entregada boolean DEFAULT false,
  fechaentrega timestamp without time zone,
  estado integer NOT NULL DEFAULT 1,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notificacionespendientes_pkey PRIMARY KEY (id),
  CONSTRAINT notificacionespendientes_idusuario_fkey FOREIGN KEY (idusuario) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.proproyecto (
  id integer NOT NULL DEFAULT nextval('proproyecto_id_seq'::regclass),
  nombreproyecto character varying NOT NULL,
  nroproyecto character varying NOT NULL,
  idtipoproyecto integer NOT NULL,
  idpais integer NOT NULL,
  direccion1 character varying,
  direccion2 character varying,
  ciudad character varying,
  provincia character varying,
  codigopostal character varying,
  idzonahoraria integer,
  fechainicio date,
  fechafinalizacion date,
  valorproyecto numeric,
  idtipomoneda integer,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT proproyecto_pkey PRIMARY KEY (id),
  CONSTRAINT proproyecto_idtipoproyecto_fkey FOREIGN KEY (idtipoproyecto) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT proproyecto_idpais_fkey FOREIGN KEY (idpais) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT proproyecto_idzonahoraria_fkey FOREIGN KEY (idzonahoraria) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT proproyecto_idtipomoneda_fkey FOREIGN KEY (idtipomoneda) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT proproyecto_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT proproyecto_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.roleaccaccess (
  id integer NOT NULL DEFAULT nextval('roleaccaccess_id_seq'::regclass),
  roleid bigint NOT NULL,
  resourceid bigint NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT roleaccaccess_pkey PRIMARY KEY (id),
  CONSTRAINT roleaccaccess_roleid_fkey FOREIGN KEY (roleid) REFERENCES public.authroles(id),
  CONSTRAINT roleaccaccess_resourceid_fkey FOREIGN KEY (resourceid) REFERENCES public.accresources(id),
  CONSTRAINT roleaccaccess_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT roleaccaccess_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.tratrabajador (
  id integer NOT NULL DEFAULT nextval('tratrabajador_id_seq'::regclass),
  nombres character varying NOT NULL,
  apellidos character varying NOT NULL,
  idtipodocumento integer NOT NULL,
  nrodocumento character varying NOT NULL,
  idempresa integer NOT NULL,
  idusuario integer,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  correo character varying,
  idresponsable integer,
  CONSTRAINT tratrabajador_pkey PRIMARY KEY (id),
  CONSTRAINT tratrabajador_idtipodocumento_fkey FOREIGN KEY (idtipodocumento) REFERENCES public.genlistadoopciones(id),
  CONSTRAINT tratrabajador_idempresa_fkey FOREIGN KEY (idempresa) REFERENCES public.empempresa(id),
  CONSTRAINT tratrabajador_idusuario_fkey FOREIGN KEY (idusuario) REFERENCES public.authusuarios(id),
  CONSTRAINT tratrabajador_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT tratrabajador_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id),
  CONSTRAINT tratrabajador_idResponsable_fkey FOREIGN KEY (idresponsable) REFERENCES public.tratrabajador(id)
);
CREATE TABLE public.useraccaccess (
  id integer NOT NULL DEFAULT nextval('useraccaccess_id_seq'::regclass),
  userid integer NOT NULL,
  resourceid bigint NOT NULL,
  permissionlevelid integer DEFAULT 2,
  estado integer NOT NULL DEFAULT 1,
  idusuariocreacion integer,
  idusuariomodificacion integer,
  fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fechamodificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT useraccaccess_pkey PRIMARY KEY (id),
  CONSTRAINT useraccaccess_userid_fkey FOREIGN KEY (userid) REFERENCES public.authusuarios(id),
  CONSTRAINT useraccaccess_resourceid_fkey FOREIGN KEY (resourceid) REFERENCES public.accresources(id),
  CONSTRAINT useraccaccess_permissionlevelid_fkey FOREIGN KEY (permissionlevelid) REFERENCES public.accpermissionlevels(id),
  CONSTRAINT useraccaccess_idusuariocreacion_fkey FOREIGN KEY (idusuariocreacion) REFERENCES public.authusuarios(id),
  CONSTRAINT useraccaccess_idusuariomodificacion_fkey FOREIGN KEY (idusuariomodificacion) REFERENCES public.authusuarios(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  phone character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);